# .github/workflows/deploy-web.yml
name: Deploy Web .NET para AWS Elastic Beanstalk

on:
  push:
    branches:
      - development # Incluído para build e push da imagem Docker
      - master      # Para build, push e deploy para produção

env:
  AWS_REGION: us-east-2 # Sua região AWS
  ECR_REPOSITORY_WEB: crm-web-repo # Nome do repositório ECR para a imagem web
  EB_APPLICATION_NAME_WEB: crm-web-app # Nome da aplicação Elastic Beanstalk para o web
  EB_ENVIRONMENT_NAME_WEB_PROD: crm-web-env-prod # Nome do ambiente Elastic Beanstalk para produção
  # REMOVIDO: EB_ENVIRONMENT_NAME_WEB_DEV, pois o deploy será sempre para produção
  API_URL_PROD: ${{ secrets.API_URL_PROD }} # URL da sua API de produção (do segredo)
  # REMOVIDO: API_URL_DEV, pois a API será sempre configurada para produção

jobs:
  build-and-deploy: # Nome do job ajustado para refletir o comportamento
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write' # Necessário para o OIDC

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x' # Ajustado para .NET 6.0

      - name: Restaurar dependências
        # Assumindo que a solução web é CRM-WEB.sln e está na pasta src/
        run: dotnet restore src/CRM.WEB.sln # Restaurar apenas o projeto web para otimizar

      - name: Build do Projeto Web
        # Assumindo que o projeto web é CRM.Web.csproj e está na pasta src/CRM.Web/
        run: dotnet build src/CRM.WEB.sln --no-restore --configuration Release

      # Removido o passo de Executar Testes Unitários (Web) conforme sua solicitação

      - name: Configurar credenciais AWS (via OIDC)
        # Este passo é necessário para autenticar com a AWS para ECR e Elastic Beanstalk
        # Ele será executado APENAS para a branch master
        if: github.ref == 'refs/heads/master'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }} # Sua role de deploy do GitHub Actions (pode ser a mesma da API)
          aws-region: ${{ env.AWS_REGION }}

      - name: Login no Amazon ECR
        id: login-ecr
        # Este passo será executado APENAS para a branch master
        if: github.ref == 'refs/heads/master'
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build e Push da imagem Docker para ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        working-directory: ./src/CRM.Web # Importante: O Dockerfile está dentro da pasta CRM.Web
        # Este passo será executado APENAS para a branch master
        if: github.ref == 'refs/heads/master'
        run: |
          # Build e push com a tag SHA do commit
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY_WEB }}:$IMAGE_TAG -f Dockerfile .
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY_WEB }}:$IMAGE_TAG

          # Também tag com :latest e push (para que o EB sempre puxe a última)
          docker tag $ECR_REGISTRY/${{ env.ECR_REPOSITORY_WEB }}:$IMAGE_TAG $ECR_REGISTRY/${{ env.ECR_REPOSITORY_WEB }}:latest
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY_WEB }}:latest
        shell: bash

      - name: Criar Dockerrun.aws.json
        id: create-dockerrun
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG_FOR_EB: latest
          # AJUSTADO: Sempre usar as variáveis de ambiente de produção
          API_URL_FOR_EB: ${{ env.API_URL_PROD }}
          ASPNETCORE_ENV_FOR_EB: Production
        # Este passo será executado APENAS para a branch master
        if: github.ref == 'refs/heads/master'
        run: |
          cat > Dockerrun.aws.json <<EOF
          {
            "AWSEBDockerrunVersion": "1",
            "Image": {
              "Name": "${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_WEB }}:${{ env.IMAGE_TAG_FOR_EB }}",
              "Update": "true"
            },
            "Ports": [
              {
                "ContainerPort": 80
              }
            ],
            "Environment": [
              {
                "Name": "API_BASE_URL", # Nome da variável de ambiente que sua aplicação .NET espera
                "Value": "${{ env.API_URL_FOR_EB }}"
              },
              {
                "Name": "ASPNETCORE_ENVIRONMENT",
                "Value": "${{ env.ASPNETCORE_ENV_FOR_EB }}"
              }
            ],
            "Logging": "/var/log/nginx"
          }
          EOF
          echo "Dockerrun.aws.json criado com sucesso."
        shell: bash

      - name: Instalar AWS Elastic Beanstalk CLI
        if: github.ref == 'refs/heads/master' # Instala apenas se for para deploy de produção
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awsebcli --upgrade --user
          echo "$HOME/.local/bin" >> $GITHUB_PATH
        shell: bash

      - name: Gerar pacote de deploy
        if: github.ref == 'refs/heads/master' # Gera pacote apenas se for para deploy de produção
        run: |
          zip deploy.zip Dockerrun.aws.json
          echo "deploy.zip criado com sucesso, contendo apenas Dockerrun.aws.json na raiz."
        shell: bash

      - name: Deploy para AWS Elastic Beanstalk (Produção)
        id: deploy_eb
        if: github.ref == 'refs/heads/master' # Executa deploy APENAS para a branch master
        run: |
          eb init ${{ env.EB_APPLICATION_NAME_WEB }} --region ${{ env.AWS_REGION }} --platform docker --no-verify-ssl
          eb use ${{ env.EB_ENVIRONMENT_NAME_WEB_PROD }}
          eb deploy --label ${{ github.sha }} --timeout 10
        shell: bash
